### ISSUE TITLE
Hi, I got some tiny error

### ISSUE THREAD

**Issue by lucasjinreal** [ribtoks/yannpp#1]
Saw your excellent work on reddit, can you help me why this happens?

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open file ../data/train-images-idx3-ubyte
Aborted (core dumped)
```

But the data exactly exist and I unzip it

**Comment by ribtoks** [comment]
@jinfagang compiled executable takes path to `data/` dir as the first parameter. If the data is in the repo and unzipped, then you can just start exe like `mnist_training ../data/`

**Comment by lucasjinreal** [comment]
I am just using like that. send ../data/, but the concated path is not readable in C++.... however that file exists

**Comment by ribtoks** [comment]
@jinfagang ok, does it work if you specify full path to `data/` directory? Can you let me know which OS are you using? If it's Windows, it should be "..\data\ "

**Comment by ribtoks** [comment]
@jinfagang also from your error "cannot open file ../data/train-images-idx3-ubyte" - you know that this path is calculated from working directory where you start the exe (not where the exe is located). Please check that this relative path is valid for your case.

**Comment by lucasjinreal** [comment]
OK,. I found the problem
